name: Packer Build Custom Image

on:
  push:
    branches:
      - main
env:
  PRODUCT_VERSION: "1.11.2"

jobs:
  packer-build:
    name: Build Packer Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and run integration tests
        env:
          FLASK_ENV: testing
          PYTEST_CURRENT_TEST: "True"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pytest --maxfail=5 --disable-warnings -v

      - name: Build application artifact
        run: |
          mkdir build
          cp -rf src app.py requirements.txt build/
          cd build
          zip -r webapp.zip ./src ./app.py ./requirements.txt
          cd ../
          mv -f build/webapp.zip ./webapp.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Packer Init
        run: packer init ./aws.pkr.hcl

      - name: Packer Validate
        run: packer validate ./aws.pkr.hcl

      - name: Packer Build
        run: packer build ./aws.pkr.hcl | tee build.log

      - name: Extract AMI ID from Packer Build Output
        run: |
          AMI_ID=$(grep 'artifact,0,id' build.log | cut -d',' -f6 | cut -d':' -f2)
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV
        id: get_ami_id

      - name: Share AMI with DEMO Account
        run: |
          aws ec2 modify-image-attribute \
            --image-id ${{ env.AMI_ID }} \
            --launch-permission "Add=[{UserId=${{ secrets.DEMO_ACCOUNT_ID }}}]"
        env:
          AWS_REGION: us-west-2